root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/main ./cmd/api"
entrypoint = ["./tmp/main"]

include_ext = ["go"]
exclude_dir = ["vendor", "tmp"]

delay = 500
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true