// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UserStatus.
const (
	Active   UserStatus = "active"
	Disabled UserStatus = "disabled"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Disabled:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code Stable, machine-readable error code.
		//
		// Example: invalid_credentials
		Code string `json:"code"`

		// Message Human-readable presentation text. Never contains internal details.
		//
		// Example: Invalid email or password
		Message string `json:"message"`
	} `json:"error"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email A bare RFC 5322 mailbox address (no display-name form).
	Email    string `json:"email"`
	Password string `json:"password"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RefreshResponse defines model for RefreshResponse.
type RefreshResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int64  `json:"expires_in"`

	// RefreshToken A newly rotated opaque credential; the previous one is now invalid.
	RefreshToken string `json:"refresh_token"`

	// TokenType Example: Bearer
	TokenType string `json:"token_type"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email A bare RFC 5322 mailbox address (no display-name form).
	Email    string `json:"email"`
	Password string `json:"password"`

	// Phone E.164 format.
	//
	// Example: +15551234567
	Phone *string `json:"phone,omitempty"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	// User A user's public profile. Never includes credential material
	// (password hash, refresh token hash) or other infrastructure
	// fields.
	User User `json:"user"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds until the access token expires.
	ExpiresIn int64 `json:"expires_in"`

	// RefreshToken Opaque credential; returned only once and never stored raw.
	RefreshToken string `json:"refresh_token"`

	// TokenType Example: Bearer
	TokenType string `json:"token_type"`

	// User A user's public profile. Never includes credential material
	// (password hash, refresh token hash) or other infrastructure
	// fields.
	User User `json:"user"`
}

// User A user's public profile. Never includes credential material
// (password hash, refresh token hash) or other infrastructure
// fields.
type User struct {
	CreatedAt time.Time `json:"created_at"`

	// Email A bare RFC 5322 mailbox address (no display-name form).
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	Id            openapi_types.UUID `json:"id"`

	// Phone Example: +15551234567
	Phone         *string    `json:"phone,omitempty"`
	PhoneVerified bool       `json:"phone_verified"`
	Status        UserStatus `json:"status"`
}

// UserStatus defines model for User.Status.
type UserStatus string

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	Token string `json:"token"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = ErrorResponse

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = VerifyEmailRequest
